--CREATING TABLES FOR THE GLOBAL DATABASE--

CREATE TABLE IF NOT EXISTS USERS (
        USER_ID SERIAL PRIMARY KEY,
        USERNAME VARCHAR(50) NOT NULL UNIQUE,
        PASSWORD VARCHAR(100) NOT NULL,
        ROLE VARCHAR(20) NOT NULL CHECK (ROLE IN ('global_admin', 'store_admin'))
);

CREATE TABLE IF NOT EXISTS SUPPLIERS (
        SUPPLIER_ID SERIAL PRIMARY KEY,
        SUPPLIER_NAME VARCHAR(100) NOT NULL,
        CONTACT_NAME VARCHAR(100) NOT NULL,
        CONTACT_EMAIL VARCHAR(100) NOT NULL,
        PHONE_NUMBER VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
        PRODUCT_ID SERIAL PRIMARY KEY,
        PRODUCT_NAME VARCHAR(100) NOT NULL,
        PRODUCT_BRAND VARCHAR(50) NOT NULL,
        CATEGORY_ID VARCHAR(50) NOT NULL,
        SUPPLIER_ID INTEGER,
        IS_DELETED BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS SKUS (
        SKU_ID SERIAL PRIMARY KEY,
        PRODUCT_ID INTEGER NOT NULL,
        SKU_NAME VARCHAR(100) NOT NULL,
        SIZE VARCHAR(20) NOT NULL,
        COST_PRICE DECIMAL(10, 2) NOT NULL,
        SELLING_PRICE DECIMAL(10, 2) NOT NULL,
        IS_DELETED BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS STORES (
        STORE_ID SERIAL PRIMARY KEY,
        STORE_NAME VARCHAR(100) NOT NULL,
        ZIPCODE VARCHAR(255) NOT NULL,
        STORE_MANAGER_ID INTEGER, 
        IS_ACTIVE BOOLEAN DEFAULT TRUE,
        FOREIGN KEY (STORE_MANAGER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS CENTRALIZED_STOCK_LOG (
        LOG_ID SERIAL PRIMARY KEY,
        SKU_ID INTEGER NOT NULL,
        STORE_ID INTEGER NOT NULL,
        ACTION VARCHAR(50) CHECK (ACTION IN ('SOLD', 'STOCKED', 'RESTOCKED', 'REMOVED')) NOT NULL,
        QUANTITY INTEGER NOT NULL,
        ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        COMMENT TEXT,
        FOREIGN KEY (SKU_ID) REFERENCES SKUS(SKU_ID),
        FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID) 
);

--INSERTING DUMMY DATA INTO TABLES--

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES 
        ('admin_user', 'hashed_password_1', 'global_admin'),
        ('store_manager_1', 'hashed_password_2', 'store_admin'),
        ('store_manager_2', 'hashed_password_3', 'store_admin');

INSERT INTO SUPPLIERS (SUPPLIER_NAME, CONTACT_NAME, CONTACT_EMAIL, PHONE_NUMBER) VALUES 
        ('ABC Supplies', 'John Doe', 'john.doe@abc.com', '123-456-7890'),
        ('XYZ Enterprises', 'Jane Smith', 'jane.smith@xyz.com', '234-567-8901'),
        ('Global Goods', 'Alice Johnson', 'alice.johnson@globalgoods.com', '345-678-9012');

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_BRAND, CATEGORY_ID, SUPPLIER_ID, IS_DELETED) VALUES 
        ('Tea', 'Tapal', 'Grocery', 1, FALSE),
        ('Dish Cleaner', 'Squeezy', 'Cleaning', 2, FALSE),
        ('Cooking Oil', 'Sunflower', 'Grocery', 3, FALSE),
        ('Hand Soap', 'Lifebuoy', 'Personal Care', 1, FALSE);

INSERT INTO SKUS (PRODUCT_ID, SKU_NAME, SIZE, COST_PRICE, SELLING_PRICE, IS_DELETED) VALUES 
        (1, 'Tapal Tea - Pack of 50', '50g', 10.00, 15.00, FALSE),
        (1, 'Tapal Tea - Pack of 100', '100g', 10.00, 15.00, FALSE),
        (2, 'Squeezy Dish Cleaner - 500ml', '500ml', 25.00, 40.00, FALSE),
        (3, 'Sunflower Cooking Oil - 1L', '1L', 60.00, 85.00, FALSE),
        (4, 'Lifebuoy Hand Soap - 250ml', '250ml', 20.00, 30.00, FALSE);


INSERT INTO STORES (STORE_NAME, ZIPCODE, STORE_MANAGER_ID, IS_ACTIVE)VALUES 
        ('Store A', '10001', 2, TRUE),  
        ('Store B', '20002', 3, TRUE);



